pathwar/pathwar

web/package.json, web/src/actions/userSession.js, web/src/api/index.js, web/src/api/userSession.js, web/src/components/App.js, web/src/components/ProtectedRoute.js, web/src/components/SiteWrapper.js, web/src/components/levels/LevelCardPreview.js, web/src/components/pages/LoginPage.js, web/src/components/pages/LogoutPage.js, web/src/constants/actionTypes.js, web/src/reducers/userSessionReducer.js
Creates protected routes, creates user ping checking user token, create logout routine.
=> Web Folder - Protected routes, login and logout routines

Dockerfile, Makefile, docker-compose.yml, pkg/randstring/randstring.go
=> Add Keycloak

netlify.toml
=> chore: build web directory on change only

netlify.toml, web/src/components/ProtectedRoute.js, web/src/components/challenges/ChallengeCardPreview.js, web/src/components/tournament/AllTeamsOnTournamentList.js, web/src/pages/TournamentPage.js, web/src/pages/app.js, web/src/styles/layout/loader.css, web/src/styles/layout/loader.module.css
Improve list fetching feedbacks on tournament page.
=> feat: ux-improement: improving list loadings

go/cmd/pathwar/main.go, go/go.mod, go/pkg/pwcompose/compose.go, go/pkg/pwcompose/config.go
=> `pathwar compose prepare`

go/pkg/pwcompose/compose.go, go/pkg/pwcompose/config.go
=> feat: pathwar compose up

go/go.mod, go/go.sum, go/pkg/pwcompose/compose.go, go/pkg/pwcompose/config.go
`
| CHALLENGE NAME | CONTAINER ID | NAME  | VERSION | PORTS | STATUS  | CREATED |
`
Name of column
=> Pwcompose ps

go/cmd/pathwar/main.go, go/pkg/pwagent/daemon.go
=> chore: placeholder code for agent daemon

go/cmd/pwinit/main.go, go/pkg/pwcompose/compose.go
fix: fixed an issue with entrypoint not being parsed properly when a challenges is composed of multiple services
=> fix: fixed chmod issue with on-init script in pwinit

go/pkg/pwagent/daemon.go, go/pkg/pwagent/nginx.go
=> fix: fix agent start/restart/loop

go/pkg/pwagent/nginx.go, go/pkg/pwcompose/compose.go, go/pkg/pwcompose/types.go
=> fix: improve varnames

go/cmd/pathwar/main.go, go/go.mod, go/go.sum
=> feat: use secure rand seed

go.mod, go.sum, go/cmd/pathwar/main.go, go/cmd/pathwar/main_test.go
=> feat: setup bearer

.circleci/config.yml, .github/ISSUE_TEMPLATE/bug_report.md, Dockerfile, docs/Makefile, docs/gen.sum, go/Makefile, go/gen.sum, go/pkg/pwapi/pwapi.pb.go, go/pkg/pwapi/pwapi.pb.gw.go, go/pkg/pwdb/pwdb.pb.go, go/pkg/pwinit/pwinit.pb.go, go/pkg/pwsso/pwsso.pb.go, swagger.yaml, tool/docker-protoc/Dockerfile, tool/docker-protoc/Makefile, tool/screenshoter/Dockerfile
=> feat: go1.14

.gitignore
=> fix: added screenshoter bin to gitignore file

rules.mk
=> chore: bump rulesmk

.dockerignore, .gitignore, Dockerfile, deployments/agent-dev/Makefile, deployments/agent-dev/docker-compose.yml, deployments/platform-dev/Makefile, deployments/platform-dev/docker-compose.yml, go/Makefile, go/gen.sum, tool/docker-agent/Dockerfile
+ small fixes related to deployments
=> feat: add agent-dev deployment

deployments/watchtower/Makefile, deployments/watchtower/docker-compose.yml
=> feat: add watchtower

deployments/platform-dev/docker-compose.yml, tool/forestadmin/Dockerfile
=> fix: repair forestadmin dev deployment

Dockerfile.agent, tool/docker-agent/Dockerfile
=> feat: up-to-date docker agent

go/cmd/pathwar/main.go
=> feat: use hostname as default agent name

Dockerfile.agent, deployments/agent-dev/Makefile
=> feat: new agent-dev deployment helper

Dockerfile.agent
=> fix: docker agent build

go/pkg/pwapi/api_challenge-subscription-validate_test.go
=> chore: test that challenge contains validations after a successful validation

deployments/nginx-proxy/Makefile, deployments/nginx-proxy/docker-compose.yml
=> chore: configure nginx-proxy deployment

deployments/platform-dev/.env.example, deployments/platform-dev/docker-compose.yml
=> chore: customizable platform-dev deployment

deployments/platform-dev/Makefile
=> fix: 'make flushdb' wasn't flushing all the needed volumes

deployments/platform-dev/Makefile
=> chore: add 'make sqldb' on platform-dev deployment

go/cmd/pathwar/main.go, go/cmd/pathwar/main_test.go, go/pkg/pwapi/httpclient.go
=> feat: add 'pathwar client METHOD PATH ARGS' new command

.gitattributes, .mailmap, AUTHORS, Makefile, go/Makefile, go/gen.sum
=> fix: ensure pwinit exists before running packr

go/pkg/pwdb/migrations.go
=> fix: typo in challenge debug migration bundle

.circleci/config.yml, go/pkg/pwagent/daemon.go
=> feat: daemon prints instance list from api in debug mode

go.sum, go/pkg/pwapi/httpclient.go, go/pkg/pwapi/httpclient_test.go, go/pkg/pwsso/testing.go
not sure it breaks something or not -> missing unit test(s)
=> chore: refactor pathwar client

go/cmd/pathwar/main.go
=> feat: add an helper that dumps the pwinit binary

Makefile, go/Makefile, go/gen.sum, rules.mk
=> chore: 'make docker.build' builds all the docker images

go/pkg/pwagent/nginx.go
=> feat: added websocket proxy_pass to agent generated nginx config file

go/pkg/pwapi/api_season-challenge-get.go
=> feat: GET /season-challenge now returns instances nginx_url

go/Makefile, go/gen.sum, go/pkg/pwagent/nginx.go, rules.mk
* enforce robots.txt from nginx
* configure nginx to pass missing HTTP headers
* add new rules to Makefile to make it easier to dev locally
* make local-api
* make local-agent
* make preprod-agent
* make agent-down
* make agent-nginx-config
* make api-down
=> feat(agent): enforce disallow robots.txt on challenges + add missing HTTP headers + refactor Makefile

Makefile, rules.mk
=> fix: docker makefile rules

go.mod, go.sum, go/pkg/pwsso/testing.go
=> chore: switch to moul.io/roundtripper for http client

challenges/web/helloworld/front/on-init
=> fix: typo in helloworld on-init script

web/src/components/challenges/ChallengeValidateButton.js, web/src/components/team/CreateTeamButton.js, web/src/components/team/CreateTeamStampCard.js, web/src/pages/ChallengeDetailsPage.js, web/src/pages/SeasonPage.js
Creating a simple form validation to check if data (passphrase and comment) are empty before sending to the API.
=> fix: Creating a simple validation on validate fields to prevent submit of empty data

go/pkg/pwapi/api_agent-list-instances_test.go, go/pkg/pwapi/api_season-challenge-get_test.go, go/pkg/pwapi/api_season-challenge-list_test.go, go/pkg/pwdb/migrations.go, go/pkg/pwdb/testing.go, web/tests/api.test.js
=> fix: split migrations between essential vs unit tests

.github/workflows/ci.yml
=> fix: use github actions for CI

go.mod, go.sum, go/cmd/pathwar/main.go, go/pkg/pwapi/server.go
=> fix: make pathwar api killable with signals

.circleci/config.yml, .github/workflows/ci.yml
=> chore: run golangci-lint only on github actions

go/pkg/pwdb/migrations.go
=> fix: run migrations in transactions

web/src/components/challenges/ChallengeCloseButton.js, web/src/pages/ChallengeDetailsPage.js, web/src/styles/globalStyle.js
- Adjust isClosed var in details page, preventing blank page when challenge not purchased - #524 
- Adjust close and solve button availability when challenge not purchased
- Minor fix: Add css normalize to landing page globalStyle
=> fix: blank details page when challenge not purchased, css normalize

web/src/pages/index.js, web/src/styles/globalStyle.js
=> fix: Sets dark theme based on preferences from the user, code of conduct link

web/static/_redirects, web/static/goget-pathwar-land-pathwar.html
=> chore: prepare web for new go import (#531)

web/package-lock.json, web/package.json, web/src/pages/app.js
=> feat(web): enable sentry (#534)

web/package-lock.json, web/src/actions/seasons.js, web/src/pages/SeasonPage.js
=> fix: Repeated call, missing calls when SPA navigating

go/Makefile, go/cmd/pathwar/main.go, go/gen.sum
=> feat: automatically retry to connect to MySQL on startup if connection is not yet ready

go/pkg/pwcompose/compose.go
=> feat: show pathwar's nginx container in 'pathwar compose ps'

.gitignore
=> fix: added .vscode to gitignore file

.gitattributes, rules.mk
=> chore: mark new attributes as linguist-vendored + add check script

.circleci/config.yml, challenges/Makefile, challenges/challenge.mk, challenges/web/captcha-luigi/Makefile, challenges/web/captcha-luigi/docker-compose.yml, challenges/web/captcha-mario/Makefile, challenges/web/captcha-mario/docker-compose.yml, challenges/web/helloworld/Makefile, challenges/web/helloworld/docker-compose.yml, challenges/web/imageboard/Makefile, challenges/web/imageboard/docker-compose.yml, challenges/web/imageboard/front/Dockerfile, challenges/web/training-brute/Makefile, challenges/web/training-brute/docker-compose.yml, challenges/web/training-brute/front/Dockerfile, challenges/web/training-http/Makefile, challenges/web/training-http/docker-compose.yml, challenges/web/training-include/Makefile, challenges/web/training-include/docker-compose.yml, challenges/web/training-sqli/Makefile, challenges/web/training-sqli/docker-compose.yml, challenges/web/upload-hi/Makefile, challenges/web/upload-hi/docker-compose.yml
* fix typos in challenges
* refactor challenge Makefiles and docker-compose.yml to add the challenge version and make it easier to maintain
=> fix: typos in challenges' dockerfiles + refactor

.gitignore, challenges/challenge.mk
=> chore: add new challenge helpers

AUTHORS, go.mod, go.sum, go/Makefile, go/gen.sum, go/internal/tools/tools.go
=> chore: configure CompileDaemon for auto-restarting go API and Agent

go.mod, go.sum, go/cmd/pathwar/main.go, go/cmd/pwinit/main.go
=> feat: add ascii-banners on long-running processes to help debugging

go/cmd/pathwar/cli.go, go/cmd/pathwar/main.go, go/pkg/pwapi/httpclient.go
* split main
* rename `pathwar client` into `pathwar rawclient`
* `pathwar cli @me`
* `pathwar cli teams`
* `pathwar cli challenges`
* `pathwar cli challenge-buy ID...`
* `pathwar cli coupon-validate COUPON...`
=> feat: 'pathwar cli'

web/src/actions/seasons.js, web/src/api/seasons.js, web/src/components/challenges/ChallengeBuyButton.js, web/src/components/challenges/ChallengeList.js, web/src/pages/ChallengeDetailsPage.js, web/src/pages/ChallengesPage.js, web/src/state/seasonReducer.js
Adjusting challenge buy routine with new params, removing some dead code related to buy routine.
=> fix: Buy callenge routine new params (flavor_id, season_id)

challenges/web/captcha-luigi/front/on-init
=> fix: typo in captcha-luigi on-init

challenges/web/captcha-mario/front/on-init
=> fix: typo in captcha-mario on-init file

web/src/components/challenges/ChallengeValidateForm.js
- Set comments to not be required in challenge validate
- Remove comment field validation logic
=> fix: comment not required in challenge validation

web/src/actions/userSession.js, web/src/components/challenges/ChallengeCard.js, web/src/pages/ChallengeDetailsPage.js
- Remove logic using the is_default key
- Adjust post preferences to use right active_season_id
- Remove is_latest and version tags from challenge card
=> fix: active season id on preferences post, remove tags is_latest and version

web/src/components/season/AllTeamsOnSeasonList.js, web/src/pages/StatisticsPage.js
Update all teams list table inside the statistics page to show team name, cash, and date joined.
Also remove link from team name.
=> feat: Update statistics table related to teams, show cash and more

web/src/actions/userSession.js, web/src/components/SiteWrapper.js, web/src/components/challenges/ChallengeCard.js, web/src/components/challenges/ChallengeValidateForm.js, web/src/components/coupon/ValidateCouponForm.js, web/src/pages/ChallengeDetailsPage.js, web/src/pages/app.js
~~- [ ] Move season dropdown to navbar (Test)~~ (Aborted, Dropdown is not working properly inside navbar, that's a Tabler issue and need a little extra effort on top of it)
=> feat: Navbar update, insert cash and more

web/src/components/challenges/ChallengeBuyButton.js, web/src/components/challenges/ChallengeCard.js, web/src/components/challenges/ChallengeSolveInstances.js, web/src/pages/ChallengeDetailsPage.js
=> feat: Update challenge list card, and internal behavior of status showing and buttons

web/src/components/SiteWrapper.js, web/src/components/challenges/ChallengeBuyButton.js, web/src/components/challenges/ChallengeCard.js, web/src/pages/ChallengeDetailsPage.js
=> fix: UI General, challenge card, logo, remove profile menu

web/src/pages/app.js, web/src/pages/index.js, web/static/chat-init.js
- Inserting chat button in home page and app
- Comment unused component inside app.js file
=> feat: Insert chat in Home page and App

go/pkg/pwapi/api_user-get-session.go
=> fix: do not use emails as usernames

web/src/actions/userSession.js
Push extra info about the user and current session to $crisp.
=> feat: crisp config - user and session

web/package-lock.json, web/package.json, web/src/actions/seasons.js, web/src/actions/userSession.js, web/src/api/seasons.js, web/src/api/userSession.js, web/src/components/coupon/ValidateCouponForm.js, web/src/utils/fireworks-dispatcher.js
=> feat: Fireworks animation on challenge validate and coupon

go/cmd/pathwar/cli.go
=> feat: cli command to validate a challenge

go/pkg/pwapi/api_user-get-session.go, go/pkg/pwapi/auth.go
=> feat: testers can see testing season, admin can see all seasons

go/pkg/pwapi/api_admin-challenge-redump.go
=> fix: challenge redump sql call didn't find the challenge instances

challenges/_register.sh, go/cmd/pathwar/compose.go
=> WIP feat: added challenge redump call after register

tool/db_backup.sh
=> feat: added pwdb backup script

deployments/platform-dev/Makefile
=> chore: add backup command

deployments/agent-dev/docker-compose.yml, deployments/platform-dev/Makefile, deployments/platform-dev/docker-compose.yml
=> chore: update fr1 infra

.gitignore, .vscode/launch.json
[![Image from Gyazo](https://i.gyazo.com/1963d41bbdeebb3befe1ff272f3bc5f7.png)](https://gyazo.com/1963d41bbdeebb3befe1ff272f3bc5f7)
=> chore: go debugger setup

AUTHORS, go/Makefile, go/gen.sum, go/pkg/pwsso/token.go, tool/screenshoter/go.sum
=> fix: don't report error that token used before issued

Dockerfile, Dockerfile.agent, go/internal/tools/tools.go
=> fix: docker build

challenges/web/helloworld/front/www/index.html, challenges/web/helloworld/front/www/you-lose.html, challenges/web/helloworld/front/www/you-win.html, challenges/web/imageboard/front/www/index.php, challenges/web/training-brute/front/www/index.php, challenges/web/training-brute/front/www/source_2.txt, challenges/web/training-http/front/www/default.php, challenges/web/training-http/front/www/header.php, challenges/web/training-http/front/www/step1.php, challenges/web/training-http/front/www/step2.php, challenges/web/training-http/front/www/step3.php, challenges/web/training-http/front/www/step4.php, challenges/web/training-include/front/www/home.php, challenges/web/training-include/front/www/include1.php, challenges/web/training-include/front/www/include2.php, challenges/web/training-include/front/www/include3.php, challenges/web/training-include/front/www/include4.php, challenges/web/training-include/front/www/include5.php, challenges/web/training-include/front/www/index.php, challenges/web/training-include/front/www/passphrase.php, challenges/web/training-sqli/front/www/default.php, challenges/web/training-sqli/front/www/header.php, challenges/web/training-sqli/front/www/step1.php, challenges/web/training-sqli/front/www/step2.php
For existing challenges:
- Corrects text content grammar/syntax; makes content more concise for clarity
=> chore: Proofread challenges copy

web/src/components/ProtectedRoute.js
This PR creates a refreshing routine due to token expiration and in case it is not able to get a new token it says to the user that he needs to refresh the page.
It also has a refactoring removing the class way of doing things from the `ProtectedRoutes` component
=> feat: Refresh keycloak token, inform user when session expires

.gitignore, crowdin-challenges.yml
=> chore: fix crowdin config for challenges

web/.env.production, web/netlify.toml
=> chore: update netlify config

web/netlify.toml
=> chore: update gatsby env

web/src/components/SiteWrapper.js
=> chore: adjust var in file

web/src/pages/404.js, web/src/translations/en.json, web/src/translations/es.json, web/src/translations/fr.json, web/src/translations/it.json, web/src/translations/pt.json, web/src/translations/ru.json, web/src/translations/zh.json
It creates a new 404 page for gatsby application respecting the overall UI identity of the app.
=> feat: new gatsby main 404 page

web/src/components/challenges/ChallengeCard.js
=> chore: increase challenges density

web/src/pages/ChallengeDetailsPage.js, web/src/pages/app.js, web/src/translations/en.json, web/src/translations/es.json, web/src/translations/fr.json, web/src/translations/it.json, web/src/translations/pt.json, web/src/translations/ru.json, web/src/translations/zh.json
It removes a remaining app route that was present in the SPA routing system and adjusts the not available page message.
=> fix: (app-route) - remove remaining app route

web/src/components/challenges/ChallengeCard.js, web/src/config/tagMap.js, web/src/pages/ChallengeDetailsPage.js
It's creating a tag map to hold the tags color and keep them regular, not fixed or using a random color.
=> fix: Challenge tags colors

web/gatsby-config.js, web/package-lock.json, web/package.json, web/src/pages/index.js
It's including an analytics snippet.
=> fix: add analytics script

web/src/components/SiteWrapper.js, web/src/components/season/AllTeamsOnSeasonList.js
It's including the user gravatar in the user menu.
It's adjusting to correctly sort the users in rank by doing the correct comparison.
=> fix: User avatar, rank sorting

challenges/web/training-sqli/front/www/index.php, challenges/web/training-sqli/front/www/templates/main.html
Improve Pedagogy
add a view to the request PHP side on training SQLI
=> Training sqli request viewer2

Dockerfile.agent
Signed-off-by: Manfred Touron <94029+moul@users.noreply.github.com>
=> chore: fix pathwar/agent

challenges/crypto/binaryencoding/Makefile, challenges/crypto/binaryencoding/chal/Dockerfile, challenges/crypto/binaryencoding/chal/default.conf.template, challenges/crypto/binaryencoding/chal/on-init, challenges/crypto/binaryencoding/docker-compose.yml
Adding Semah's `BinaryEncoding` challenge in crypto category.
=> chore: add BinaryEncoding challenge

challenges/crypto/base64encoding/Makefile, challenges/crypto/base64encoding/chal/Dockerfile, challenges/crypto/base64encoding/chal/default.conf.template, challenges/crypto/base64encoding/chal/on-init, challenges/crypto/base64encoding/docker-compose.yml, challenges/crypto/binaryencoding/docker-compose.yml
Adding Semah's `Base64Encoding` challenge in crypto category.
=> chore: add Base64Encoding challenge

Dockerfile.agent
Signed-off-by: Manfred Touron <94029+moul@users.noreply.github.com>
=> chore: use binary with docker-compose-dab for agent

go/pkg/pwagent/daemon.go, go/pkg/pwagent/nginx.go
Signed-off-by: Manfred Touron <94029+moul@users.noreply.github.com>
=> chore: support custom agent port

.github/workflows/go.yml
=> test(ci): bump golangci-lint on CI

go/cmd/pathwar/dev.go, go/cmd/pathwar/events.go, go/cmd/pathwar/main.go
=> feat: add events command

.github/workflows/go.yml
=> chore: update golangci-lint config

go/cmd/pathwar/dev.go
=> feat: adapt dev challenge run command to allow deploy with it

web/src/state/organizationsReducer.js
=> feat(web): redux add update list of teams on create team action

web/src/components/organization/AllTeamsOnOrganization.js
=> fix(web): add details button in list team in organization details page

web/src/constants/apiErrorsCode.js
=> fix(web): add error msg for buying challenge cash issue

web/src/constants/apiErrorsCode.js
=> fix: add message error for invalid passphrase
